### PR TITLE
Fix inline markup causing table cells to split

### PR DESCRIPTION
**Pull request by thaJeztah**
relates to / addresses https://github.com/docker/cli/issues/2985

Before this change, markup inside a table cell would introduce a newline, which resulted in those parts creating a new table row/cell:

       ┌───────────────────────────────┬───────────────────────────┐
       │Col1                           │ Col2                      │
       ├───────────────────────────────┼───────────────────────────┤
       │row|one                        │ Col1 should not wrap.     │
       ├───────────────────────────────┼───────────────────────────┤
       │row two                        │ no                        │
       ├───────────────────────────────┼───────────────────────────┤
       │|                              │                           │
       ├───────────────────────────────┼───────────────────────────┤
       │wrap                           │                           │
       ├───────────────────────────────┼───────────────────────────┤
       │row three                      │ Inline                    │
       ├───────────────────────────────┼───────────────────────────┤
       │cursive markup should not wrap │                           │
       ├───────────────────────────────┼───────────────────────────┤
       │row four                       │ Inline                    │
       ├───────────────────────────────┼───────────────────────────┤
       │code markup should not wrap    │                           │
       └───────────────────────────────┴───────────────────────────┘

After this change, markup does not introduce a newline, and content is correctly
rendered in a single table row / cell:

       ┌───────────────────────────────┬───────────────────────────┐
       │Col1                           │ Col2                      │
       ├───────────────────────────────┼───────────────────────────┤
       │row|one                        │ Col1 should not wrap.     │
       ├───────────────────────────────┼───────────────────────────┤
       │row two                        │ no|wrap                   │
       ├───────────────────────────────┼───────────────────────────┤
       │row three                      │ Inline cursive markup     │
       │                               │ should not wrap           │
       ├───────────────────────────────┼───────────────────────────┤
       │row four                       │ Inline core markup should │
       │                               │ not wrap                  │
       └───────────────────────────────┴───────────────────────────┘

Closes #68

### CODE REVIEW

**Comment by thaJeztah** [comment]
temporarily rebased on top of https://github.com/cpuguy83/go-md2man/pull/68, otherwise the test would fail

**Comment by thaJeztah** [comment]
Fix did not work for long table cells (which are wrapped in `tableCellStart` / `tableCellEnd`), so I had to do some refactoring and moved the logic to `handleTableCell()`, which made the `handleText()` function redundant

**Comment by cpuguy83** [comment]
@thaJeztah What's the status of this one?

**Comment by thaJeztah** [comment]
It's been a while, but I _think_ this one was working ok.

I see I included https://github.com/cpuguy83/go-md2man/pull/68 in this one, which could be merged separately.


And I see this needs a rebase

**Review by cpuguy83 — APPROVED** [review]
This looks ok and doesn't break or change any existing tests.

image


Maybe @estesp could also take a look.

**Review by kolyshkin — APPROVED** [review]
LGTM

**Pull request merged**
