### PR TITLE
chore: set go minimal version to 1.11

### PR DESCRIPTION
**Pull request by QuentinBrosse**
The codebase is compatible with Go 1.12.

### CODE REVIEW

**Comment by marco-m** [comment]
hello @cpuguy83 any chance to merge this PR? Thanks :-)

**Comment by cpuguy83** [comment]
What is this fixing?

**Comment by marco-m** [comment]
> What is this fixing?

Good question. I arrived at this PR from https://github.com/scaleway/scaleway-cli/pull/585. I will let @QuentinBrosse give the correct answer :-)

**Comment by QuentinBrosse** [comment]
Hi @cpuguy83,
We have a dependency on your package and we want to support Go 1.11.

If I try to build it with Go 1.11, I have [this error](https://travis-ci.org/scaleway/scaleway-cli/jobs/615451235?utm_medium=notification&utm_source=github_status):
```
go build github.com/cpuguy83/go-md2man/v2/md2man: module requires Go 1.12
```

Thanks. :)

**Pull request merged**
