### PR TITLE
Fix table parsing/processing for v2

### PR DESCRIPTION
**Pull request by estesp**
Fixes: #34 

Tables were not being rendered correctly with the v2 blackfriday API,
including a nil pointer deref.

Signed-off-by: Phil Estes <estesp@gmail.com>

### CODE REVIEW

**Comment by estesp** [comment]
Am going to add a table test as well with another commit

**Comment by estesp** [comment]
Test added; this should be ready for review

**Comment by cpuguy83** [comment]
Fixes panic, looks like we have a trailing `.TE`

image

and 

> /usr/bin/tbl:<standard input>:151: premature end of file

from `man`

**Comment by rhatdan** [comment]
Thanks @estesp and @cpuguy83

**Pull request merged**
